-- =============================================
-- SUPERSTORE SALES ANALYSIS | SQL on Snowflake
-- Dataset: 51,252 rows | 25,035 orders | 4,873 customers
-- Author: Saswat Betta
-- =============================================


-- =============================================
-- PART 1: DATA CLEANING
-- =============================================

-- 1.1 Convert ORDER_DATE and SHIP_DATE from VARCHAR to DATE
ALTER TABLE SUPERSTORE_DATA ADD COLUMN ORDER_DATE_CLEAN DATE;
ALTER TABLE SUPERSTORE_DATA ADD COLUMN SHIP_DATE_CLEAN DATE;

UPDATE SUPERSTORE_DATA
SET ORDER_DATE_CLEAN = TRY_TO_DATE(SPLIT_PART(ORDER_DATE, ' ', 1), 'DD-MM-YYYY'),
    SHIP_DATE_CLEAN  = TRY_TO_DATE(SPLIT_PART(SHIP_DATE, ' ', 1), 'DD-MM-YYYY');

ALTER TABLE SUPERSTORE_DATA DROP COLUMN ORDER_DATE;
ALTER TABLE SUPERSTORE_DATA DROP COLUMN SHIP_DATE;
ALTER TABLE SUPERSTORE_DATA RENAME COLUMN ORDER_DATE_CLEAN TO ORDER_DATE;
ALTER TABLE SUPERSTORE_DATA RENAME COLUMN SHIP_DATE_CLEAN TO SHIP_DATE;

-- 1.2 Fix encoding issues in PRODUCT_NAME (278 rows)
UPDATE SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
SET PRODUCT_NAME = REPLACE(REPLACE(REPLACE(PRODUCT_NAME, 'Ã‚Â€Â', '"'), 'Ã‚', ''), 'Â', '')
WHERE PRODUCT_NAME LIKE '%Ã%' OR PRODUCT_NAME LIKE '%Â%';

-- 1.3 Remove duplicate rows (38 duplicates)
CREATE OR REPLACE TABLE SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA AS
SELECT * FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY ORDER_ID, PRODUCT_ID ORDER BY ORDER_ID) AS RN
    FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
) WHERE RN = 1;
ALTER TABLE SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA DROP COLUMN RN;

-- 1.4 Standardize MARKET column
UPDATE SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
SET MARKET = CASE
    WHEN UPPER(MARKET) = 'US' THEN 'US'
    WHEN UPPER(MARKET) = 'EU' THEN 'EU'
    WHEN UPPER(MARKET) = 'APAC' THEN 'APAC'
    WHEN UPPER(MARKET) = 'LATAM' THEN 'LATAM'
    WHEN UPPER(MARKET) = 'EMEA' THEN 'EMEA'
    WHEN UPPER(MARKET) = 'AFRICA' THEN 'Africa'
    WHEN UPPER(MARKET) = 'CANADA' THEN 'Canada'
    ELSE INITCAP(MARKET)
END;

-- 1.5 Trim whitespace from all text columns
UPDATE SUPERSTORE_DATA
SET CATEGORY = TRIM(CATEGORY),
    CITY = TRIM(CITY),
    COUNTRY = TRIM(COUNTRY),
    CUSTOMER_ID = TRIM(CUSTOMER_ID),
    CUSTOMER_NAME = TRIM(CUSTOMER_NAME),
    MARKET = TRIM(MARKET),
    ORDER_ID = TRIM(ORDER_ID),
    ORDER_PRIORITY = TRIM(ORDER_PRIORITY),
    PRODUCT_ID = TRIM(PRODUCT_ID),
    PRODUCT_NAME = TRIM(PRODUCT_NAME),
    REGION = TRIM(REGION),
    SEGMENT = TRIM(SEGMENT),
    SHIP_MODE = TRIM(SHIP_MODE),
    STATE = TRIM(STATE),
    SUB_CATEGORY = TRIM(SUB_CATEGORY),
    DISCOUNT_BIN = TRIM(DISCOUNT_BIN);

-- 1.6 Verify cleaned data
SELECT COUNT(*) AS TOTAL_ROWS FROM SUPERSTORE_DATA;


-- =============================================
-- PART 2: BUSINESS KPIs & OVERVIEW
-- =============================================

-- 2.1 Overall Business KPIs
SELECT 
    SUM(SALES) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS PROFIT_MARGIN,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(SALES) / NULLIF(COUNT(DISTINCT ORDER_ID), 0), 2) AS AVG_ORDER_VALUE,
    ROUND(AVG(DISCOUNT) * 100, 2) AS AVG_DISCOUNT,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS,
    ROUND(SUM(PROFIT) / NULLIF(COUNT(DISTINCT ORDER_ID), 0), 2) AS AVG_PROFIT_PER_ORDER,
    ROUND(SUM(QUANTITY) * 1.0 / NULLIF(COUNT(DISTINCT ORDER_ID), 0), 2) AS AVG_QTY_PER_ORDER
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA;

-- 2.2 Null Check (Data Quality)
SELECT 
    COUNT(*) - COUNT(ORDER_ID) AS ORDER_ID_NULL,
    COUNT(*) - COUNT(CUSTOMER_NAME) AS CUSTOMER_NULL,
    COUNT(*) - COUNT(SALES) AS SALES_NULL,
    COUNT(*) - COUNT(PROFIT) AS PROFIT_NULL
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA;


-- =============================================
-- PART 3: SEGMENT, CATEGORY & REGION ANALYSIS
-- =============================================

-- 3.1 Segment Performance
SELECT SEGMENT,
    SUM(SALES) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS MARGIN_PCT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY SEGMENT ORDER BY TOTAL_SALES DESC;

-- 3.2 Category Performance
SELECT CATEGORY,
    SUM(SALES) AS SALES,
    ROUND(SUM(PROFIT), 2) AS PROFIT,
    SUM(QUANTITY) AS QUANTITY,
    ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS MARGIN_PCT
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY CATEGORY ORDER BY SALES DESC;

-- 3.3 Sub-Category Performance
SELECT SUB_CATEGORY,
    ROUND(SUM(SALES), 2) AS SALES,
    ROUND(SUM(PROFIT), 2) AS PROFIT,
    ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS MARGIN_PCT
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY SUB_CATEGORY ORDER BY SALES DESC;

-- 3.4 Regional Performance
SELECT REGION,
    SUM(SALES) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS MARGIN_PCT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY REGION ORDER BY TOTAL_SALES DESC;

-- 3.5 Market Performance
SELECT MARKET,
    ROUND(SUM(SALES), 0) AS SALES,
    ROUND(SUM(PROFIT), 0) AS PROFIT,
    ROUND(SUM(PROFIT) / NULLIF(SUM(SALES), 0) * 100, 2) AS MARGIN_PCT
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY MARKET ORDER BY SALES DESC;


-- =============================================
-- PART 4: TIME-BASED ANALYSIS
-- =============================================

-- 4.1 Yearly Growth Trend
SELECT YEAR(ORDER_DATE) AS YR,
    ROUND(SUM(SALES), 0) AS SALES,
    ROUND(SUM(PROFIT), 0) AS PROFIT,
    COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY YR ORDER BY YR;

-- 4.2 Monthly Sales Trend (Year + Month)
SELECT ORDER_YEAR, ORDER_MONTH,
    SUM(SALES) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY ORDER_YEAR, ORDER_MONTH
ORDER BY ORDER_YEAR, ORDER_MONTH;

-- 4.3 Monthly Aggregated Trend
SELECT MONTH(ORDER_DATE) AS MONTH_NUM,
    ROUND(SUM(SALES), 0) AS SALES,
    COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY MONTH_NUM ORDER BY MONTH_NUM;


-- =============================================
-- PART 5: PRODUCT & CUSTOMER ANALYSIS
-- =============================================

-- 5.1 Top 5 Most Profitable Products
SELECT PRODUCT_NAME, ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY PRODUCT_NAME ORDER BY TOTAL_PROFIT DESC LIMIT 5;

-- 5.2 Top 5 Loss-Making Products
SELECT PRODUCT_NAME, ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY PRODUCT_NAME ORDER BY TOTAL_PROFIT ASC LIMIT 5;

-- 5.3 Top 10 Customers by Sales
SELECT CUSTOMER_NAME,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY CUSTOMER_NAME ORDER BY TOTAL_SALES DESC LIMIT 10;


-- =============================================
-- PART 6: SHIPPING & DISCOUNT ANALYSIS
-- =============================================

-- 6.1 Shipping Mode Distribution
SELECT SHIP_MODE, COUNT(*) AS ORDERS, ROUND(SUM(SALES), 2) AS SALES
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY SHIP_MODE ORDER BY ORDERS DESC;

-- 6.2 Discount Impact on Profit
SELECT DISCOUNT_BIN,
    COUNT(*) AS ORDERS,
    ROUND(SUM(SALES), 0) AS SALES,
    ROUND(SUM(PROFIT), 0) AS PROFIT,
    ROUND(AVG(PROFIT), 2) AS AVG_PROFIT
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY DISCOUNT_BIN ORDER BY DISCOUNT_BIN;

-- 6.3 Avg Order Value by Segment
SELECT SEGMENT, ROUND(AVG(SALES), 2) AS AVG_ORDER_VALUE
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY SEGMENT ORDER BY AVG_ORDER_VALUE DESC;


-- =============================================
-- PART 7: STATISTICAL ANALYSIS
-- =============================================

-- 7.1 Descriptive Stats (Mean, Std, Percentiles, Skewness, Kurtosis)
SELECT 
    'SALES' AS COL, COUNT(SALES) AS CNT, ROUND(AVG(SALES), 2) AS MEAN,
    ROUND(STDDEV(SALES), 2) AS STD, MIN(SALES) AS MIN_VAL,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY SALES) AS P25,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY SALES) AS P50,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY SALES) AS P75,
    MAX(SALES) AS MAX_VAL,
    ROUND(SKEW(SALES), 2) AS SKEWNESS,
    ROUND(KURTOSIS(SALES), 2) AS KURTOSIS
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
UNION ALL
SELECT 'PROFIT', COUNT(PROFIT), ROUND(AVG(PROFIT), 2), ROUND(STDDEV(PROFIT), 2),
    MIN(PROFIT), PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY PROFIT),
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY PROFIT),
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY PROFIT),
    MAX(PROFIT), ROUND(SKEW(PROFIT), 2), ROUND(KURTOSIS(PROFIT), 2)
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
UNION ALL
SELECT 'QUANTITY', COUNT(QUANTITY), ROUND(AVG(QUANTITY), 2), ROUND(STDDEV(QUANTITY), 2),
    MIN(QUANTITY), PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QUANTITY),
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY QUANTITY),
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QUANTITY),
    MAX(QUANTITY), ROUND(SKEW(QUANTITY), 2), ROUND(KURTOSIS(QUANTITY), 2)
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
UNION ALL
SELECT 'DISCOUNT', COUNT(DISCOUNT), ROUND(AVG(DISCOUNT), 2), ROUND(STDDEV(DISCOUNT), 2),
    MIN(DISCOUNT), PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY DISCOUNT),
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY DISCOUNT),
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY DISCOUNT),
    MAX(DISCOUNT), ROUND(SKEW(DISCOUNT), 2), ROUND(KURTOSIS(DISCOUNT), 2)
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
UNION ALL
SELECT 'SHIPPING_COST', COUNT(SHIPPING_COST), ROUND(AVG(SHIPPING_COST), 2),
    ROUND(STDDEV(SHIPPING_COST), 2), MIN(SHIPPING_COST),
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY SHIPPING_COST),
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY SHIPPING_COST),
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY SHIPPING_COST),
    MAX(SHIPPING_COST), ROUND(SKEW(SHIPPING_COST), 2), ROUND(KURTOSIS(SHIPPING_COST), 2)
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA;

-- 7.2 Outlier Detection (IQR Method)
SELECT COUNT(*) AS PROFIT_OUTLIERS FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA WHERE PROFIT < -55.17 OR PROFIT > 91.95;
SELECT COUNT(*) AS SHIPPING_OUTLIERS FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA WHERE SHIPPING_COST < -30.15 OR SHIPPING_COST > 57.21;
SELECT COUNT(*) AS SALES_OUTLIERS FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA WHERE SALES < -299 OR SALES > 581;


-- =============================================
-- PART 8: SALES PER UNIT ANALYSIS
-- =============================================

-- 8.1 SPU by Category
SELECT CATEGORY,
    ROUND(AVG(SALES_PER_UNIT), 2) AS AVG_SPU,
    ROUND(MEDIAN(SALES_PER_UNIT), 2) AS MEDIAN_SPU,
    SUM(QUANTITY) AS TOTAL_QTY
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY CATEGORY ORDER BY AVG_SPU DESC;

-- 8.2 SPU by Sub-Category
SELECT SUB_CATEGORY,
    ROUND(AVG(SALES_PER_UNIT), 2) AS AVG_SPU,
    COUNT(*) AS ORDERS,
    ROUND(AVG(PROFIT_MARGIN), 2) AS AVG_MARGIN
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY SUB_CATEGORY ORDER BY AVG_SPU DESC;

-- 8.3 SPU by Discount Bin
SELECT DISCOUNT_BIN,
    ROUND(AVG(SALES_PER_UNIT), 2) AS AVG_SPU,
    ROUND(AVG(PROFIT_MARGIN), 2) AS AVG_MARGIN
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY DISCOUNT_BIN ORDER BY DISCOUNT_BIN;

-- 8.4 SPU Yearly Trend
SELECT ORDER_YEAR,
    ROUND(AVG(SALES_PER_UNIT), 2) AS AVG_SPU,
    ROUND(MEDIAN(SALES_PER_UNIT), 2) AS MEDIAN_SPU
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA
GROUP BY ORDER_YEAR ORDER BY ORDER_YEAR;


-- =============================================
-- PART 9: POWER BI VIEW
-- =============================================

CREATE OR REPLACE VIEW SUPERSTOREDB.PUBLIC.VW_SUPERSTORE_POWERBI AS
SELECT 
    ORDER_ID, ORDER_DATE, SHIP_DATE,
    DATEDIFF('day', ORDER_DATE, SHIP_DATE) AS SHIPPING_DAYS,
    SHIP_MODE, CUSTOMER_ID, CUSTOMER_NAME, SEGMENT,
    MARKET, REGION, COUNTRY, STATE, CITY,
    CATEGORY, SUB_CATEGORY, PRODUCT_ID, PRODUCT_NAME,
    SALES, QUANTITY, DISCOUNT, PROFIT, SHIPPING_COST,
    ORDER_PRIORITY, ORDER_YEAR, ORDER_MONTH, ORDER_QUARTER,
    ORDER_WEEK, ORDER_DAY_OF_WEEK, IS_WEEKEND, DISCOUNT_BIN,
    PROFIT_MARGIN, SALES_PER_UNIT,
    ROUND(PROFIT / NULLIF(SALES, 0) * 100, 2) AS PROFIT_PCT,
    CASE WHEN PROFIT > 0 THEN 'Profitable' ELSE 'Loss' END AS PROFIT_FLAG
FROM SUPERSTOREDB.PUBLIC.SUPERSTORE_DATA;
